[package]
name = "test-mailing-list-call"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[lib]
name = "test_mailinglistcall"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/common/" }

