[package]
name = "deserialize-error"
version = "0.1.0"
authors = ["Mateusz Górski <mateusz@casperlabs.io>"]
edition = "2018"

[lib]
name = "deserialize_error"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std"]

[dependencies]
cl_std = { path = "../../common", package = "casperlabs-contract-ffi" }
