[package]
name = "transfer-purse-to-purse"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
name = "transfer_purse_to_purse"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std"]

[dependencies]
cl_std = { path = "../../common", package = "casperlabs-contract-ffi" }
